---
# tasks file for task-shortcuts

- set_fact:
    base_path: "{{ oem_base_path }}"
    icon_path: "/etc/skel/Desktop"
    file_mode: 0755
  when: icon_mode == 'oem'
- set_fact:
    base_path: "{{ global_base_path }}"
    icon_path: "/usr/local/share/applications"
    file_mode: 0644
  when: icon_mode == 'user'
- set_fact: bin_path="{{ base_path }}/vmtools/bin"
- set_fact: uug_ansible_wrapper="{{ bin_path }}/uug_ansible_wrapper.py"

- name: Create VMTools bin
  file:
      path: "{{ bin_path }}"
      state: directory
- name: Install Ansible wrapper script
  copy:
      src: uug_ansible_wrapper.py
      dest: '{{ uug_ansible_wrapper }}'
      mode: 0755
- name: Install JMU Tux icon
  copy:
      src: jmu-tux.svg
      dest: "{{ base_path }}/jmu-tux.svg"
      mode: 0644
- name: Copy shortcut to desktop file directory
  template:
      src: desktop-template.desktop.j2
      dest: "{{ icon_path }}/jmucs_config.desktop"
      mode: "{{ file_mode }}" 

