---
# handlers file for robot-pkgs

- name: USB controllers warning
  command: >-
    zenity --warning --text {{ usb_warning_msg }} --width=300 --height=200
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.uid }}"
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
  ignore_errors: yes
- name: Reload udev rules
  command: /sbin/udevadm control --reload-rules
