---
- name: Configure UUG VM
  hosts: all
  become: true
  roles:
    - { role: common, tags: always }
    - { role: wireless-printing, tags: always }
    - { role: filezilla, tags: always }
    - { role: basic-prog-pkgs, tags: ["cs101"] }
    - { role: adv-prog-pkgs, tags: ["cs261"] }
    - { role: robot-pkgs, tags: ["cs354"] }
    - { role: eclipse, tags: ["cs149", "cs159"] }
    - { role: jgrasp, tags: ["cs149"] }
    - { role: drjava, tags: ["cs149"] }
    - { role: aptana, tags: ["cs101"] }
    - { role: finch, tags: ["cs101"] }
    - { role: task-shortcuts, tags: always, icon_mode: user }
