---
# vars file for robot-pkgs
ros_release: melodic

# Keep UMD first to prefer downloads from there
ros_repos:
  - "http://mirror.umd.edu/packages.ros.org/ros/ubuntu"
  - "http://packages.ros.org/ros/ubuntu"

ros_packages:
  - ros-{{ros_release}}-desktop-full
  - ros-{{ros_release}}-sound-play
  - ros-{{ros_release}}-ar-track-alvar
  - gazebo9
  - rviz
  - g++

usb_warning_msg: |
  "<b>USB Contollers missing</b>
  In order to effectively connect robots to the VM
  ECHI/xHCI controllers need to be installed from
  VirtualBox. See <a href='https://jmunixusers.github.io/presentations/vm/virtualbox-extension-pack.html'>these instructions</a> for
  more information on how to install them"
