---
# tasks file for Finch
- name: Check Finch
  stat:
    path: '{{ finch.zip }}'
  register: st
- block:
    - name: Create Finch directory
      file:
        path: '{{ finch.install_path }}'
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Fetch Finch zip
      get_url:
        url: '{{ finch.url }}'
        dest: '{{ finch.zip }}'
        checksum: 'sha1:{{ finch.hash }}'
        force: yes
    - name: Unpack Finch zip
      unarchive:
        dest: '{{ finch.install_path }}'
        src: '{{ finch.zip }}'
        owner: root
        group: root
        mode: "0755"
  when: st.stat.checksum|default("") != finch.hash
- name: Install Finch udev rule
  copy:
    src: 55-finch.rules
    dest: '/etc/udev/rules.d/'
    owner: root
    group: root
    mode: "0644"
- name: Install Finch extra - dance2.py
  copy:
    src: dance2.py
    dest: '{{ finch.install_path }}'
    owner: root
    group: root
    mode: "0644"
- name: Install Finch extra - maze.py
  copy:
    src: maze.py
    dest: '{{ finch.install_path }}'
    owner: root
    group: root
    mode: "0644"
- name: Create Finch profile entries
  blockinfile:
    path: '{{ global_profile_path }}'
    marker: "## {mark} Finch profile entries ##"
    block: |
      export HIDAPI_LIB_PATH={{ finch.install_path }}
      export PYTHONPATH=$PYTHONPATH:{{ finch.install_path }}
  notify:
    - Suggest restart
