---

# Tasks to only be run on virtualized guest OSes.

# The apt database can be fairly large and make the image unnecessarily large
# so removing it before shipping allows us to ship a smaller image.
- name: Clean the apt database
  command: apt-get clean
  # This will always report as changed otherwise
  changed_when: False
  args:
    warn: no

# The USB 2/3 controllers are only available with the Virtualbox
# Extensions which are non-free software and available only under the Oracle
# PUEL. We should ensure we have not accidentally included them.
- name: Validate missing USB 2/3 controllers
  shell: lspci | grep -i -e EHCI -e xHCI
  register: lspci_output
  failed_when: lspci_output.rc == 0
  changed_when: False

- name: Fill disk with zeros to assist with compression
  shell: dd if=/dev/zero of=/bigfile bs=1M; sync; rm /bigfile
  changed_when: False
