#!/usr/bin/env bash

# Performs basic bootstrapping to prepare a machine for the main cs-vm-build
# installation. Mostly, this installs a few dependencies and then runs an OEM
# Ansible playbook.

#--
# Emits a message to the user preceeded by ==> to stdout.
#
# Expected parameters:
#   $1: The string to print
#--
user () {
    echo "==> ${1}"
}

#---
# Emits an error message and exits the script to stderr.
#
# Expected parameters:
#  $1: The string to print
#---
error () {
    echo "!!! ${1}" 1>&2
    echo "Exiting." 1>&2
    exit 1
}

#---
# If running with `sudo`, returns the home directory of the user who invoked
# `sudo`. Otherwise, returns the home directory of the current user.
#---
home_directory() {
    if [ -z "$SUDO_USER" ]; then
        echo "$HOME"
    else
        getent passwd "$SUDO_USER" | cut -d ':' -f 6
    fi
}

#---
# Installs VirtualBox Guest Additions if ISO file is present
#---
install_additions() {
    local iso_file
    local additions_dir
    iso_file="$(home_directory)/VBoxGuestAdditions.iso"
    additions_dir="$(home_directory)/additions"

    if [ ! -f "$iso_file" ]; then
        user "VirtualBox Additions disk missing. Skipping installation."
        return
    fi

    mkdir "$additions_dir"
    mount -o loop,ro "$iso_file" "$additions_dir"

    # Guest additions installation returns error 2 on success
    "${additions_dir}/VBoxLinuxAdditions.run" || true

    umount "$additions_dir"
    rm -r "$additions_dir"
    rm "$iso_file"
}

#---
# Performs the actual preparation of the machine
#---
main () {
    if [ "$(id -u)" -ne "0" ]; then
        user "Not running as root. Automatically retrying with sudo."
        exec sudo "$0"
        exit $?
    fi

    # Ensure this runs from the root directory of the Ansible git directory
    local project_dir
    project_dir="$(dirname "$(dirname "$(realpath "$0")")")"
    if cd "$project_dir"; then
        user "Running from $project_dir"
    else
        error "Unable to cd to $project_dir"
    fi

    user "Updating apt package cache"
    apt-get update

    user "Installing prerequisite packages"
    apt-get install -V ansible git aptitude gcc make perl \
        || error "Unable to install prerequisite packages"

    user "Attempting to install VBox Guest Additions"
    install_additions

    user "Running ansible OEM playbook"
    ansible-playbook -i hosts -c local -t oem oem.yml \
        || error "Playbook failed to complete successfully"
}

# Actually run the main function
main
