#!/usr/bin/env bash

set-output() (
  local name="$1"
  local value="$2"
  # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
  echo "$name=$value" >> "$GITHUB_OUTPUT"
)

MIRROR_URL="https://mirror.cs.jmu.edu/pub/ubuntu-iso/$UBUNTU_RELEASE"
ISO_NAME="$(curl -sL "$MIRROR_URL/SHA256SUMS" | grep desktop | head -n 1 | cut -d'*' -f 2)"
VERSION="$(echo "$ISO_NAME" | cut -d'-' -f 2)"
cat << EOF > packer/ubuntu-version.auto.pkrvars.hcl
ubuntu_version = {
  version         = "$UBUNTU_RELEASE"
  patched_version = "$VERSION"
}
EOF

set-output "version" "$VERSION"
set-output "iso_file" "$ISO_NAME"
set-output "mirror_url" "$MIRROR_URL"
