#!/usr/bin/env bash

repo_url="https://github.com/jmunixusers/cs-vm-build"

error_text=$(cat <<- EOF
    <b>ERROR</b>
    There were errors running the playbook. Please try to run it again. If you
    continue to experience issues, please report a bug on
    <a href="${repo_url}/issues/new">GitHub</a>
EOF
)

success_text=$(cat <<- EOF
    <b>SUCCESS</b>
    The script completed successfully.
EOF
)

root_text=$(cat <<- EOF
    <b>WARNING</b>
    It is recommended to not run this tool with root permissions.
EOF
)

no_args_text=$(cat <<- EOF
    <b>ERROR</b>
    Not enough informaton was provided.
EOF
)

gksudo_msg="This tool makes modifications to your system. In order to run, it requires your password."

if [ -z "$1" ]; then
    zenity --error "${no_args_text}"
    exit 1
fi

if [ -$UID -eq 0 ]; then
    zenity --warning "${root_text}"
    exit 1
fi

if gksudo --message "$gksudo_msg" -- ansible-pull --url "$repo_url" --purge -i hosts -t "$1"; then
    zenity --info --text="${success_text}"
    exit_status=0
else
    zenity --error --text="${error_text}"
    exit_status=1
fi
exit $exit_status
