#!/usr/bin/env bash

repo_url="https://github.com/jmunixusers/cs-vm-build"

error_text=$(cat <<- EOF
    <b>ERROR</b>
    There were errors running the playbook. Please try to run it again. If you
    continue to experience issues, please report a bug on
    <a href="https://github.com/jmunixusers/cs-vm-build/issues/new>GitHub</a>
EOF
)

success_text=$(cat <<- EOF
    <b>SUCCESS</b>
    The script completed successfully.
EOF
)

no_root_text=$(cat <<- EOF
    <b>ERROR</b>
    This must be run as root.
EOF
)

if [ -z "$1" ]; then
    zenity --error "${no_root_text}"
    exit 1;
fi

if ansible-pull --url "$repo_url" --purge -i hosts -t "$1"; then
    zenity --info --text="${success_text}"
    exit_status=0
else
    zenity --error --text="${error_text}"
    exit_status=1
fi
exit $exit_status
