---
# vars file for Finch
finch:
  url: 'https://www.birdbraintechnologies.com/downloads/finch/FinchPython120.zip'
  zip: '{{ global_base_path }}/FinchPython120.zip'
  hash: '841a7f7ca3a11678ecb6319e9983f87c57eb80da'
  install_path: '{{ global_base_path }}/FinchPython'
