---
name: Packer lint workflow
on:
  pull_request:
    paths:
      - 'packer/*'
jobs:
  Lint:
    name: Run Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip3 install demjson
      - name: Run jsonlint
        run: |
          jsonlint packer/*json
      - name: Fetch and unzip packer nightly
        run: |
          wget -nv -O $HOME/packer.zip https://github.com/hashicorp/packer/releases/download/nightly/packer_linux_amd64.zip
          unzip -d $HOME/packer $HOME/packer.zip
      - name: Packer validate
        run: |
          $HOME/packer/pkg/packer_linux_amd64 validate packer/oem-build.json
          $HOME/packer/pkg/packer_linux_amd64 validate packer/oem-build-beta.json
